airport_BMV = Airport.create(code: 'BMV', name: 'Buôn Ma Thuột', name_unsigned: 'Buon Ma Thuot', short_name: 'BMT', is_domestic: 1)
airport_CAH = Airport.create(code: 'CAH', name: 'Cà Mau', name_unsigned: 'Ca Mau', short_name: 'CMau', is_domestic: 1)
airport_VCA = Airport.create(code: 'VCA', name: 'Cần Thơ', name_unsigned: 'Can Tho', short_name: 'CTho', is_domestic: 1)
airport_VCS = Airport.create(code: 'VCS', name: 'Côn Đảo', name_unsigned: 'Con Dao', short_name: 'CDao', is_domestic: 1)
airport_VCL = Airport.create(code: 'VCL', name: 'Chu Lai', name_unsigned: 'Chu Lai', short_name: 'CLai', is_domestic: 1)
airport_DLI = Airport.create(code: 'DLI', name: 'Đà Lạt', name_unsigned: 'Da Lat', short_name: 'DLat', is_domestic: 1)
airport_DAD = Airport.create(code: 'DAD', name: 'Đà Nẵng', name_unsigned: 'Da Nang', short_name: 'DNang', is_domestic: 1)
airport_DIN = Airport.create(code: 'DIN', name: 'Điện Biên', name_unsigned: 'Dien Bien', short_name: 'DBien', is_domestic: 1)
airport_VDH = Airport.create(code: 'VDH', name: 'Đồng Hới', name_unsigned: 'Dong Hoi', short_name: 'DHoi', is_domestic: 1)
airport_HAN = Airport.create(code: 'HAN', name: 'Hà Nội', name_unsigned: 'Ha Noi', short_name: 'HN', is_domestic: 1)
airport_HPH = Airport.create(code: 'HPH', name: 'Hải Phòng', name_unsigned: 'Hai Phong', short_name: 'HP', is_domestic: 1)
airport_HUI = Airport.create(code: 'HUI', name: 'Huế', name_unsigned: 'Hue', short_name: 'Hue', is_domestic: 1)
airport_CXR = Airport.create(code: 'CXR', name: 'Nha Trang', name_unsigned: 'Nha Trang', short_name: 'NTrang', is_domestic: 1)
airport_PXU = Airport.create(code: 'PXU', name: 'Pleiku', name_unsigned: 'Pleiku', short_name: 'Pleiku', is_domestic: 1)
airport_PQC = Airport.create(code: 'PQC', name: 'Phú Quốc', name_unsigned: 'Phu Quoc', short_name: 'PQuoc', is_domestic: 1)
airport_UIH = Airport.create(code: 'UIH', name: 'Quy Nhơn', name_unsigned: 'Quy Nhon', short_name: 'QNhon', is_domestic: 1)
airport_VKG = Airport.create(code: 'VKG', name: 'Rạch Giá', name_unsigned: 'Rach Gia', short_name: 'RGia', is_domestic: 1)
airport_SGN = Airport.create(code: 'SGN', name: 'Hồ Chí Minh', name_unsigned: 'Ho Chi Minh', short_name: 'HCM', is_domestic: 1)
airport_VII = Airport.create(code: 'VII', name: 'Vinh', name_unsigned: 'Vinh', short_name: 'Vinh', is_domestic: 1)
airport_TBB = Airport.create(code: 'TBB', name: 'Tuy Hòa', name_unsigned: 'Tuy Hoa', short_name: 'TuyHoa', is_domestic: 1)
airport_THD = Airport.create(code: 'THD', name: 'Thanh Hóa', name_unsigned: 'Thanh Hoa', short_name: 'ThHoa', is_domestic: 1)

airport_ADL = Airport.create(code: 'ADL', name: 'Adelaide', name_unsigned: 'Adelaide', short_name: 'Adelaide', is_domestic: 0)
airport_AMS = Airport.create(code: 'AMS', name: 'Amsterdam', name_unsigned: 'Amsterdam', short_name: 'Amsterdam', is_domestic: 0)
airport_ATL = Airport.create(code: 'ATL', name: 'Atlanta Hartsfield', name_unsigned: 'Atlanta Hartsfield', short_name: 'AtlantaHartsfield', is_domestic: 0)
airport_AKL = Airport.create(code: 'AKL', name: 'Auckland', name_unsigned: 'Auckland', short_name: 'Auckland', is_domestic: 0)
airport_AUS = Airport.create(code: 'AUS', name: 'Austin', name_unsigned: 'Austin', short_name: 'Austin', is_domestic: 0)
airport_DPS = Airport.create(code: 'DPS', name: 'Bali (Denpasar)', name_unsigned: 'Bali (Denpasar)', short_name: 'Bali(Denpasar)', is_domestic: 0)
airport_BKK = Airport.create(code: 'BKK', name: 'Bangkok', name_unsigned: 'Bangkok', short_name: 'Bangkok', is_domestic: 0)
airport_BCN = Airport.create(code: 'BCN', name: 'Barcelona', name_unsigned: 'Barcelona', short_name: 'Barcelona', is_domestic: 0)
airport_BJS = Airport.create(code: 'BJS', name: 'Beijing', name_unsigned: 'Beijing', short_name: 'Beijing', is_domestic: 0)
airport_BOS = Airport.create(code: 'BOS', name: 'Boston, Logan', name_unsigned: 'Boston, Logan', short_name: 'Boston,Logan', is_domestic: 0)
airport_BNE = Airport.create(code: 'BNE', name: 'Brisbane', name_unsigned: 'Brisbane', short_name: 'Brisbane', is_domestic: 0)
airport_PUS = Airport.create(code: 'PUS', name: 'Busan', name_unsigned: 'Busan', short_name: 'Busan', is_domestic: 0)
airport_CTU = Airport.create(code: 'CTU', name: 'Chengdu', name_unsigned: 'Chengdu', short_name: 'Chengdu', is_domestic: 0)
airport_CHI = Airport.create(code: 'CHI', name: 'Chicago IL', name_unsigned: 'Chicago IL', short_name: 'ChicagoIL', is_domestic: 0)
airport_CHC = Airport.create(code: 'CHC', name: 'Christchurch', name_unsigned: 'Christchurch', short_name: 'Christchurch', is_domestic: 0)
airport_DFW = Airport.create(code: 'DFW', name: 'Dallas Fort Worth', name_unsigned: 'Dallas Fort Worth', short_name: 'DallasFortWorth', is_domestic: 0)
airport_DRW = Airport.create(code: 'DRW', name: 'Darwin', name_unsigned: 'Darwin', short_name: 'Darwin', is_domestic: 0)
airport_DEN = Airport.create(code: 'DEN', name: 'Denver', name_unsigned: 'Denver', short_name: 'Denver', is_domestic: 0)
airport_FRA = Airport.create(code: 'FRA', name: 'Frankfurt', name_unsigned: 'Frankfurt', short_name: 'Frankfurt', is_domestic: 0)
airport_FUK = Airport.create(code: 'FUK', name: 'Fukuoka', name_unsigned: 'Fukuoka', short_name: 'Fukuoka', is_domestic: 0)
airport_GVA = Airport.create(code: 'GVA', name: 'Geneva', name_unsigned: 'Geneva', short_name: 'Geneva', is_domestic: 0)
airport_OOL = Airport.create(code: 'OOL', name: 'Gold Coast', name_unsigned: 'Gold Coast', short_name: 'GoldCoast', is_domestic: 0)
airport_CAN = Airport.create(code: 'CAN', name: 'Guangzhou', name_unsigned: 'Guangzhou', short_name: 'Guangzhou', is_domestic: 0)
airport_HGH = Airport.create(code: 'HGH', name: 'Hangzhou', name_unsigned: 'Hangzhou', short_name: 'Hangzhou', is_domestic: 0)
airport_HBA = Airport.create(code: 'HBA', name: 'Hobart', name_unsigned: 'Hobart', short_name: 'Hobart', is_domestic: 0)
airport_HNL = Airport.create(code: 'HNL', name: 'Honolulu', name_unsigned: 'Honolulu', short_name: 'Honolulu', is_domestic: 0)
airport_HKG = Airport.create(code: 'HKG', name: 'Hong Kong', name_unsigned: 'Hong Kong', short_name: 'HongKong', is_domestic: 0)
airport_CGK = Airport.create(code: 'CGK', name: 'Jakarta', name_unsigned: 'Jakarta', short_name: 'Jakarta', is_domestic: 0)
airport_KHH = Airport.create(code: 'KHH', name: 'Kaohsiung', name_unsigned: 'Kaohsiung', short_name: 'Kaohsiung', is_domestic: 0)
airport_KUL = Airport.create(code: 'KUL', name: 'Kuala Lumpur', name_unsigned: 'Kuala Lumpur', short_name: 'KualaLumpur', is_domestic: 0)
airport_LON = Airport.create(code: 'LON', name: 'London', name_unsigned: 'London', short_name: 'London', is_domestic: 0)
airport_LAX = Airport.create(code: 'LAX', name: 'Los Angeles', name_unsigned: 'Los Angeles', short_name: 'LosAngeles', is_domestic: 0)
airport_LPQ = Airport.create(code: 'LPQ', name: 'Luang Prabang', name_unsigned: 'Luang Prabang', short_name: 'LuangPrabang', is_domestic: 0)
airport_LYS = Airport.create(code: 'LYS', name: 'Lyon', name_unsigned: 'Lyon', short_name: 'Lyon', is_domestic: 0)
airport_MFM = Airport.create(code: 'MFM', name: 'Ma Cao', name_unsigned: 'Ma Cao', short_name: 'MaCao', is_domestic: 0)
airport_MAD = Airport.create(code: 'MAD', name: 'Madrid', name_unsigned: 'Madrid', short_name: 'Madrid', is_domestic: 0)
airport_MNL = Airport.create(code: 'MNL', name: 'Manila', name_unsigned: 'Manila', short_name: 'Manila', is_domestic: 0)
airport_MRS = Airport.create(code: 'MRS', name: 'Marseille', name_unsigned: 'Marseille', short_name: 'Marseille', is_domestic: 0)
airport_KNO = Airport.create(code: 'KNO', name: 'Medan - Kualanamu', name_unsigned: 'Medan - Kualanamu', short_name: 'Medan-Kualanamu', is_domestic: 0)
airport_MEL = Airport.create(code: 'MEL', name: 'Melbourne', name_unsigned: 'Melbourne', short_name: 'Melbourne', is_domestic: 0)
airport_MIA = Airport.create(code: 'MIA', name: 'Miami', name_unsigned: 'Miami', short_name: 'Miami', is_domestic: 0)
airport_MSP = Airport.create(code: 'MSP', name: 'Minneapolis/St.Paul', name_unsigned: 'Minneapolis/St.Paul', short_name: 'Minneapolis/St.Paul', is_domestic: 0)
airport_MPL = Airport.create(code: 'MPL', name: 'Montpellier', name_unsigned: 'Montpellier', short_name: 'Montpellier', is_domestic: 0)
airport_MOW = Airport.create(code: 'MOW', name: 'Moscow', name_unsigned: 'Moscow', short_name: 'Moscow', is_domestic: 0)
airport_NGO = Airport.create(code: 'NGO', name: 'Nagoya', name_unsigned: 'Nagoya', short_name: 'Nagoya', is_domestic: 0)
airport_JFK = Airport.create(code: 'JFK', name: 'New York', name_unsigned: 'New York', short_name: 'NewYork', is_domestic: 0)
airport_NCE = Airport.create(code: 'NCE', name: 'Nice', name_unsigned: 'Nice', short_name: 'Nice', is_domestic: 0)
airport_OSA = Airport.create(code: 'OSA', name: 'Osaka', name_unsigned: 'Osaka', short_name: 'Osaka', is_domestic: 0)
airport_PAR = Airport.create(code: 'PAR', name: 'Paris', name_unsigned: 'Paris', short_name: 'Paris', is_domestic: 0)
airport_PEN = Airport.create(code: 'PEN', name: 'Penang', name_unsigned: 'Penang', short_name: 'Penang', is_domestic: 0)
airport_PER = Airport.create(code: 'PER', name: 'Perth', name_unsigned: 'Perth', short_name: 'Perth', is_domestic: 0)
airport_PDX = Airport.create(code: 'PDX', name: 'Portland', name_unsigned: 'Portland', short_name: 'Portland', is_domestic: 0)
airport_PRG = Airport.create(code: 'PRG', name: 'Prague', name_unsigned: 'Prague', short_name: 'Prague', is_domestic: 0)
airport_PHL = Airport.create(code: 'PHL', name: 'Philadelphia', name_unsigned: 'Philadelphia', short_name: 'Philadelphia', is_domestic: 0)
airport_PNH = Airport.create(code: 'PNH', name: 'Phnom Penh', name_unsigned: 'Phnom Penh', short_name: 'PhnomPenh', is_domestic: 0)
airport_HKT = Airport.create(code: 'HKT', name: 'Phuket', name_unsigned: 'Phuket', short_name: 'Phuket', is_domestic: 0)
airport_ROM = Airport.create(code: 'ROM', name: 'Rome', name_unsigned: 'Rome', short_name: 'Rome', is_domestic: 0)
airport_SFO = Airport.create(code: 'SFO', name: 'San Francisco', name_unsigned: 'San Francisco', short_name: 'SanFrancisco', is_domestic: 0)
airport_SEA = Airport.create(code: 'SEA', name: 'Seattle, Tacoma', name_unsigned: 'Seattle, Tacoma', short_name: 'Seattle,Tacoma', is_domestic: 0)
airport_SEL = Airport.create(code: 'SEL', name: 'Seoul', name_unsigned: 'Seoul', short_name: 'Seoul', is_domestic: 0)
airport_ICN = Airport.create(code: 'ICN', name: 'Seoul Incheon Int', name_unsigned: 'Seoul Incheon Int', short_name: 'SeoulIncheonInt', is_domestic: 0)
airport_SHA = Airport.create(code: 'SHA', name: 'Shanghai', name_unsigned: 'Shanghai', short_name: 'Shanghai', is_domestic: 0)
airport_REP = Airport.create(code: 'REP', name: 'Siem Riep', name_unsigned: 'Siem Riep', short_name: 'SiemRiep', is_domestic: 0)
airport_SIN = Airport.create(code: 'SIN', name: 'Singapore', name_unsigned: 'Singapore', short_name: 'Singapore', is_domestic: 0)
airport_STL = Airport.create(code: 'STL', name: 'St Louis, Lambert', name_unsigned: 'St Louis, Lambert', short_name: 'StLouis,Lambert', is_domestic: 0)
airport_SUB = Airport.create(code: 'SUB', name: 'Surabaya', name_unsigned: 'Surabaya', short_name: 'Surabaya', is_domestic: 0)
airport_SYD = Airport.create(code: 'SYD', name: 'Sydney', name_unsigned: 'Sydney', short_name: 'Sydney', is_domestic: 0)
airport_TPE = Airport.create(code: 'TPE', name: 'Taipei', name_unsigned: 'Taipei', short_name: 'Taipei', is_domestic: 0)
airport_HND = Airport.create(code: 'HND', name: 'Tokyo Haneda', name_unsigned: 'Tokyo Haneda', short_name: 'TokyoHaneda', is_domestic: 0)
airport_NRT = Airport.create(code: 'NRT', name: 'Tokyo Narita', name_unsigned: 'Tokyo Narita', short_name: 'TokyoNarita', is_domestic: 0)
airport_TLS = Airport.create(code: 'TLS', name: 'Toulouse', name_unsigned: 'Toulouse', short_name: 'Toulouse', is_domestic: 0)
airport_VIE = Airport.create(code: 'VIE', name: 'Vienne', name_unsigned: 'Vienne', short_name: 'Vienne', is_domestic: 0)
airport_VTE = Airport.create(code: 'VTE', name: 'Vientiane', name_unsigned: 'Vientiane', short_name: 'Vientiane', is_domestic: 0)
airport_WAS = Airport.create(code: 'WAS', name: 'Washington', name_unsigned: 'Washington', short_name: 'Washington', is_domestic: 0)
airport_RGN = Airport.create(code: 'RGN', name: 'Yangon', name_unsigned: 'Yangon', short_name: 'Yangon', is_domestic: 0)
airport_ZRH = Airport.create(code: 'ZRH', name: 'Zurich', name_unsigned: 'Zurich', short_name: 'Zurich', is_domestic: 0)

plane_vietnam = PlaneCategory.create(category: 'vietnam airline', name: "Vietnam Airline", short_name: "VNAirline")
plane_jetstar = PlaneCategory.create(category: 'jetstar', name: "Jetstar", short_name: "Jetstar")
plane_vietjet = PlaneCategory.create(category: 'vietjet', name: "Vietjet Air", short_name: "Vietjet")

Route.create(ori_airport_id: airport_BMV.id, des_airport_id: airport_HPH.id, is_domestic: 1)
Route.create(ori_airport_id: airport_BMV.id, des_airport_id: airport_SGN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_BMV.id, des_airport_id: airport_THD.id, is_domestic: 1)
Route.create(ori_airport_id: airport_BMV.id, des_airport_id: airport_VDH.id, is_domestic: 1)
Route.create(ori_airport_id: airport_BMV.id, des_airport_id: airport_VII.id, is_domestic: 1)
Route.create(ori_airport_id: airport_BMV.id, des_airport_id: airport_HAN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_BMV.id, des_airport_id: airport_DAD.id, is_domestic: 1)

Route.create(ori_airport_id: airport_CAH.id, des_airport_id: airport_SGN.id, is_domestic: 1)

Route.create(ori_airport_id: airport_CXR.id, des_airport_id: airport_DAD.id, is_domestic: 1)
Route.create(ori_airport_id: airport_CXR.id, des_airport_id: airport_HAN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_CXR.id, des_airport_id: airport_SGN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_CXR.id, des_airport_id: airport_UIH.id, is_domestic: 1)
Route.create(ori_airport_id: airport_CXR.id, des_airport_id: airport_VDH.id, is_domestic: 1)

Route.create(ori_airport_id: airport_DAD.id, des_airport_id: airport_CXR.id, is_domestic: 1)
Route.create(ori_airport_id: airport_DAD.id, des_airport_id: airport_HAN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_DAD.id, des_airport_id: airport_PQC.id, is_domestic: 1)
Route.create(ori_airport_id: airport_DAD.id, des_airport_id: airport_SGN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_DAD.id, des_airport_id: airport_TBB.id, is_domestic: 1)
Route.create(ori_airport_id: airport_DAD.id, des_airport_id: airport_VCA.id, is_domestic: 1)
Route.create(ori_airport_id: airport_DAD.id, des_airport_id: airport_BMV.id, is_domestic: 1)
Route.create(ori_airport_id: airport_DAD.id, des_airport_id: airport_DLI.id, is_domestic: 1)
Route.create(ori_airport_id: airport_DAD.id, des_airport_id: airport_HPH.id, is_domestic: 1)
Route.create(ori_airport_id: airport_DAD.id, des_airport_id: airport_PXU.id, is_domestic: 1)
Route.create(ori_airport_id: airport_DAD.id, des_airport_id: airport_VII.id, is_domestic: 1)

Route.create(ori_airport_id: airport_DLI.id, des_airport_id: airport_DAD.id, is_domestic: 1)
Route.create(ori_airport_id: airport_DLI.id, des_airport_id: airport_HAN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_DLI.id, des_airport_id: airport_VKG.id, is_domestic: 1)
Route.create(ori_airport_id: airport_DLI.id, des_airport_id: airport_VII.id, is_domestic: 1)

Route.create(ori_airport_id: airport_HPH.id, des_airport_id: airport_BMV.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HPH.id, des_airport_id: airport_SGN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HPH.id, des_airport_id: airport_TBB.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HPH.id, des_airport_id: airport_UIH.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HPH.id, des_airport_id: airport_DAD.id, is_domestic: 1)

Route.create(ori_airport_id: airport_HUI.id, des_airport_id: airport_PQC.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HUI.id, des_airport_id: airport_SGN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HUI.id, des_airport_id: airport_HAN.id, is_domestic: 1)

Route.create(ori_airport_id: airport_PQC.id, des_airport_id: airport_DAD.id, is_domestic: 1)
Route.create(ori_airport_id: airport_PQC.id, des_airport_id: airport_HAN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_PQC.id, des_airport_id: airport_HUI.id, is_domestic: 1)
Route.create(ori_airport_id: airport_PQC.id, des_airport_id: airport_SGN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_PQC.id, des_airport_id: airport_TBB.id, is_domestic: 1)
Route.create(ori_airport_id: airport_PQC.id, des_airport_id: airport_THD.id, is_domestic: 1)
Route.create(ori_airport_id: airport_PQC.id, des_airport_id: airport_UIH.id, is_domestic: 1)
Route.create(ori_airport_id: airport_PQC.id, des_airport_id: airport_VDH.id, is_domestic: 1)
Route.create(ori_airport_id: airport_PQC.id, des_airport_id: airport_VCA.id, is_domestic: 1)
Route.create(ori_airport_id: airport_PQC.id, des_airport_id: airport_VKG.id, is_domestic: 1)

Route.create(ori_airport_id: airport_TBB.id, des_airport_id: airport_HAN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_TBB.id, des_airport_id: airport_SGN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_TBB.id, des_airport_id: airport_DAD.id, is_domestic: 1)
Route.create(ori_airport_id: airport_TBB.id, des_airport_id: airport_HPH.id, is_domestic: 1)
Route.create(ori_airport_id: airport_TBB.id, des_airport_id: airport_PQC.id, is_domestic: 1)
Route.create(ori_airport_id: airport_TBB.id, des_airport_id: airport_VII.id, is_domestic: 1)

Route.create(ori_airport_id: airport_THD.id, des_airport_id: airport_BMV.id, is_domestic: 1)
Route.create(ori_airport_id: airport_THD.id, des_airport_id: airport_PQC.id, is_domestic: 1)
Route.create(ori_airport_id: airport_THD.id, des_airport_id: airport_SGN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_THD.id, des_airport_id: airport_VDH.id, is_domestic: 1)

Route.create(ori_airport_id: airport_UIH.id, des_airport_id: airport_HAN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_UIH.id, des_airport_id: airport_SGN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_UIH.id, des_airport_id: airport_CXR.id, is_domestic: 1)
Route.create(ori_airport_id: airport_UIH.id, des_airport_id: airport_HPH.id, is_domestic: 1)
Route.create(ori_airport_id: airport_UIH.id, des_airport_id: airport_PQC.id, is_domestic: 1)

Route.create(ori_airport_id: airport_VCA.id, des_airport_id: airport_HAN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VCA.id, des_airport_id: airport_DAD.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VCA.id, des_airport_id: airport_VCS.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VCA.id, des_airport_id: airport_PQC.id, is_domestic: 1)

Route.create(ori_airport_id: airport_VCL.id, des_airport_id: airport_HAN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VCL.id, des_airport_id: airport_SGN.id, is_domestic: 1)

Route.create(ori_airport_id: airport_VCS.id, des_airport_id: airport_VCA.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VCS.id, des_airport_id: airport_SGN.id, is_domestic: 1)

Route.create(ori_airport_id: airport_VDH.id, des_airport_id: airport_HAN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VDH.id, des_airport_id: airport_SGN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VDH.id, des_airport_id: airport_BMV.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VDH.id, des_airport_id: airport_CXR.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VDH.id, des_airport_id: airport_PQC.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VDH.id, des_airport_id: airport_THD.id, is_domestic: 1)

Route.create(ori_airport_id: airport_VII.id, des_airport_id: airport_BMV.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VII.id, des_airport_id: airport_HAN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VII.id, des_airport_id: airport_TBB.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VII.id, des_airport_id: airport_DLI.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VII.id, des_airport_id: airport_DAD.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VII.id, des_airport_id: airport_SGN.id, is_domestic: 1)

Route.create(ori_airport_id: airport_VKG.id, des_airport_id: airport_SGN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_VKG.id, des_airport_id: airport_PQC.id, is_domestic: 1)

Route.create(ori_airport_id: airport_PXU.id, des_airport_id: airport_DAD.id, is_domestic: 1)
Route.create(ori_airport_id: airport_PXU.id, des_airport_id: airport_HAN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_PXU.id, des_airport_id: airport_SGN.id, is_domestic: 1)

Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_CXR.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_DAD.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_SGN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_TBB.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_VDH.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_VII.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_DLI.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_BMV.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_PQC.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_VCA.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_UIH.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_VCL.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_DIN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_HUI.id, is_domestic: 1)
Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_PXU.id, is_domestic: 1)

Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_VKG.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_VII.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_VDH.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_VCS.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_VCL.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_UIH.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_THD.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_TBB.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_PXU.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_PQC.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_HUI.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_HPH.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_HAN.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_DLI.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_DAD.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_CXR.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_CAH.id, is_domestic: 1)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_BMV.id, is_domestic: 1)

Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_BKK.id, is_domestic: 0)
Route.create(ori_airport_id: airport_HAN.id, des_airport_id: airport_SIN.id, is_domestic: 0)

Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_BKK.id, is_domestic: 0)
Route.create(ori_airport_id: airport_SGN.id, des_airport_id: airport_SIN.id, is_domestic: 0)

Route.create(ori_airport_id: airport_BKK.id, des_airport_id: airport_HAN.id, is_domestic: 0)
Route.create(ori_airport_id: airport_BKK.id, des_airport_id: airport_SGN.id, is_domestic: 0)

Route.create(ori_airport_id: airport_SIN.id, des_airport_id: airport_HAN.id, is_domestic: 0)
Route.create(ori_airport_id: airport_SIN.id, des_airport_id: airport_SGN.id, is_domestic: 0)